### ISSUE TITLE
你好，为什么要在本地建server

### ISSUE THREAD

**Issue by wengyunshang** [fq050766/AVPlayerCacheDemo#1]
m3u8下载到本地，直接访问那个文件可以吗？   为什么要在本地建server呢？

**Comment by fengqiangboy** [comment]
m3u8格式的视频播放的时候是有多个片段文件组成的，AVPlayer是不能播放每个单独的文件的，搭建本地Server就是为了模拟AVPlayer请求网络数据，这样，不用对AVPlayer做其他的操作就可以播放起来了。
